config/routes.rb
Rails.application.routes.draw do
  
  get 'comments/create'
  get 'comments/destroy'
  get 'comments/edit'
  patch 'comments/update'
  devise_for :users, path: 'user', path_names:{sign_in: 'login', sign_out: 'logout'}
  root 'home#index'
  
  resources :posts, controller:"home" do
    resources :comments #only: [:edit,:create, :destroy,:update]
  end
  
  
  # get 'home/index'
  
  # get 'home/new'

  # post 'home/create', as: 'posts'
  
  # get 'home/destroy/:post_id' =>'home#destroy', as: 'post_destroy'

  # get 'home/edit/:post_id' => 'home#edit'

  # patch 'home/update/:post_id' => 'home#update', as: 'post'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
    has_and_belongs_to_many :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments  #comment를 여러개 가진다는 뜻
    
    has_and_belongs_to_many :hashtags
    accepts_nested_attributes_for :hashtags

    #mount_uploader :image_url, ImageUploader # post 모델의 image_url 칼럼에 내가 올린 파일의 주소를 저장해줘!
end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment ,only: [:edit,:destroy,:update]
  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.user_id = current_user.id  ## 현재 유저 정보를 가져오는 것
    @comment.save

    redirect_back fallback_location: root_path
  end

  def destroy
    # @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_back fallback_location: root_path
  end

  def edit
   #  @comment = Comment.find(params[:id])
    
  end

  def update    
    # post = Post.find(params[:id]) //원래는 @가 안들어가있는데 set post로 인해서 @삽입 필수 
    respond_to do |format|
      if @comment.update(comment_params)
        format.html{ redirect_to post_path(@comment.post_id), notice: '댓글이 성공적으로 수정되었습니다' }
      else
        format.html{ render :edit } 
      end
    end
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:show,:edit,:destroy]
  before_action :set_post, only: [:show,:edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
    3.times { @post.hashtags.new }
  end

  def show
  end

  def create
    @post = Post.new(post_params)
    3.times do |x|
      tag = hashtag_params[:hashtags_attributes]["#{x}"][:title]
      addHashtag = Hashtag.find_or_create_by(title: tag)

      @post.hashtags << addHashtag
    end
    respond_to do |format|
      if @post.save
        format.html{ redirect_to root_path, notice: '게시물이 성공적으로 작성되었습니다!'}
      else
        format.html{ render :new }
      end
    end
    # params[:hashtags_attributes][0 or 1 or 2 여기는 번호가 들어감][:title] => 이렇게 뽑아야 나옴
    # "hashtags_attributes"=>
    # { "0"=>{"title"=>"하나"}, "1"=>{"title"=>"둘"}, "2"=>{"title"=>"셋"} }
  end

  def destroy
    # @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  def edit
    # @post = Post.find(params[:id])  // set post를 통해서 해결
  end

  def update    
    # post = Post.find(params[:id]) //원래는 @가 안들어가있는데 set post로 인해서 @삽입 필수 
    respond_to do |format|
      if @post.update(post_params)
        format.html{ redirect_to root_path, notice: '게시물이 성공적으로 수정되었습니다' }
      else
        format.html{ render :edit } 
      end
    end

  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  # title이랑 content만 받아와라 라는 뜻
  def post_params
    params.require(:post).permit(:title, :content)
  end
  
  def hashtag_params
    params.require(:post).permit(hashtags_attributes: [:title])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/comments/_form.html.erb
<%= params %>
<%= form_for(@comment, url:post_comment_path,method:"put") do |f| %>
    <%=f.label :content, '내 용'%>
    <br><br><br>
    <%=f.text_area :content %><br>
    <%=f.submit%>
<%end%>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<%=params%>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h2> 댓글 수정 페이지 </h2>
<%=render '/comments/form' %>

app/views/home/_form.html.erb
<%=form_for(@post) do |f| %>
    <%=f.label :title, '제 목'%>
    <%=f.text_field :title %><br>
    <%=f.label :content, '내 용'%>
    <%=f.text_area :content %><br>
    <ul>
        <%= f.fields_for :hashtags do |h| %>
            <li>
                <%= h.label :title ,"해시태그" %>
                <%= h.text_field :title %>
            </li>
        <% end%>
    </ul>

    <%=f.submit%>
<%end%>

app/views/home/create.html.erb
<%=params%>

app/views/home/edit.html.erb
<h2>수정 페이지입니다!</h2>

<%=render 'form' %>

app/views/home/index.html.erb
<div class="container-fluid">

  <h1>전체 글 목록입니다</h1>
  <%if user_signed_in?%>
  <%= link_to '새 글 쓰기', new_post_path %><br>
  <% else%>
  <div class ='text-danger' >글을 작성하려면 로그인 하세요!</div><br>
  <% end%>
        <% Post.all.each do |p| %>
            제 목 : <%=p.title%><br>

            <%= link_to post_path(p.id) do%>
                <btn>보기</btn>
            <%end %> /
            <%=link_to post_path(p.id), method: :delete do%>
                <btn>삭제</btn>
            <%end%> /
    
            <%=link_to edit_post_path(p.id) do%>
                <btn>수정</btn>
            <%end%> /
            <br>
            ================<br>
        <% end %>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm">
      One of three columns
    </div>
    <div class="col-sm">
      One of three columns
    </div>
    <div class="col-sm">
      One of three columns
    </div>
  </div>
</div>

app/views/home/new.html.erb
<h2>새 글을 작성하는 페이지입니다</h2>

<br>
<%=render 'form'%>

app/views/home/show.html.erb
제 목: <%=@post.title%>
<br>
내 용: <%=@post.content%>
<br><br>-------------------------<br>
<p>
    <%@post.hashtags.each do |h| %>
        <strong>
            #<%=h.title  %>
        </strong>
    <% end%>
</p>
<%=form_for Comment.new, url:post_comments_path(@post.id) do |f| %>
    <%= f.label :content ,'댓글 내용'%>
    <%= f.text_field :content %><br>
    <%= f.submit '댓글 작성' %>
<%end%>

<%@post.comments.each do |comment|%>
    <br><%=comment.content %>
    <%if comment.user_id == current_user.id %>
        <%= link_to '[삭제]', post_comment_path(@post.id,comment.id), method: :delete %>
        <%= link_to '[수정]', edit_post_comment_path(@post.id,comment.id)%>
    <br>
    <% end%>
<%end %>
<br>
----------------------------
<br><br>
<%= link_to '뒤로 가기', '/' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>  
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" rel="stylesheet">
    <title>RubyProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
  <div class="mx-5" background = "#000000">
    <div class="text text-right">
      
    <%if user_signed_in?%>
      <%= current_user.name %>님 안녕하세요!
        <%= link_to '로그아웃',  destroy_user_session_path, method: :delete %> /
        <%= link_to '회원 정보 수정',  edit_user_registration_path %>
    <%else%>
      <%= link_to '회원 가입', new_user_registration_path %> /
      <%= link_to '로그인', new_user_session_path %>
    <%end %>
    <br>
    </div>
  </div>

    
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">My first Board</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href= "/">Home <span class="sr-only">(current)</span></a>
      </li>
      
    <%if user_signed_in?%>
      <li class="nav-item">
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => "nav-link" %>
      </li>
      
      <li class="nav-item">
      <%= link_to 'Edit User', edit_user_registration_path, :class => "nav-link" %>
      </li>
    <%else%>
      <li class="nav-item">
      <%= link_to 'Login', new_user_session_path, :class => "nav-link"%>
      </li>
      
      <li class="nav-item">
      <%= link_to 'Sign Up', new_user_registration_path, :class => "nav-link"%>
      </li>
    <%end %>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Click Me!
        </a>
          <!-- Here's the magic. Add the .animate and .slide-in classes to your .dropdown-menu and you're all set! -->
          <div class="dropdown-menu dropdown-menu-right animate slideIn" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>